### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by aviperetz34** [RedisLabsModules/rejson#11]
Hi, tried to feed rejson with this commands:

127.0.0.1:6379> json.set x . '{"crawling": {"1days": {"regionCode": "US", "timeWindow": null, "deltaStart": {"seconds": 3600, "days": 1}, "deltaEnd": {"days": 1}, "order": "viewCount", "minViews": 5000}, "7days": {"regionCode": "US", "timeWindow": null, "deltaStart": {"seconds": 3600, "days": 7}, "deltaEnd": {"days": 7}, "order": "viewCount", "minViews": 5000}}}'
OK
127.0.0.1:6379> json.get x .crawling.1days.regionCode
(error) ERR error parsing path

am i missing something here? is it a bug or a syntax issue?

**Comment by itamarhaber** [comment]
Hi Avi,

This is a path syntax issue.

While a JSON object key can be any null-terminated string, the path syntax
for dotted notation does not allow for these to begin with digits (see
https://redislabsmodules.github.io/rejson/path/#a-note-about-json-and-path-compatability).
Instead, if you have non-compatible key names, you should revert to the
bracket notation. The following should work:

127.0.0.1:6379> json.get x '.crawling["1days"].regionCode'
"\"US\""

Note that the outer, single-quotes are need so redis-cli will treat the
contents as a single argument.

On Mar 30, 2017 11:42 PM, "aviperetz34" <notifications@github.com> wrote:

Hi, tried to feed rejson with this commands:

127.0.0.1:6379> json.set x . '{"crawling": {"1days": {"regionCode": "US",
"timeWindow": null, "deltaStart": {"seconds": 3600, "days": 1}, "deltaEnd":
{"days": 1}, "order": "viewCount", "minViews": 5000}, "7days":
{"regionCode": "US", "timeWindow": null, "deltaStart": {"seconds": 3600,
"days": 7}, "deltaEnd": {"days": 7}, "order": "viewCount", "minViews":
5000}}}'
OK
127.0.0.1:6379> json.get x .crawling.1days.regionCode
(error) ERR error parsing path

am i missing something here? is it a bug or a syntax issue?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/RedisLabsModules/rejson/issues/11>, or mute the thread

**Comment by itamarhaber** [comment]
That said, lets keep this issue open as a reminder to improve the error message in terms of verbosity and helpfulness.

**Comment by aviperetz34** [comment]
Thank you!
