### ISSUE TITLE
Error in JSON.MGET documentation

### ISSUE THREAD

**Issue by evanhuang8** [RedisLabsModules/rejson#5]
In the docs it says the MGET command's syntax is like this:

```
JSON.MGET <key> [key ...] <path>
```

While in reality, `<path>` goes first:

```
JSON.MGET <path> <key> [key ...]
```

**Comment by itamarhaber** [comment]
Thanks for finding this. So, actually the error is in the implementation, while the documentation is correct. The discrepancy should be fixed now by https://github.com/RedisLabsModules/rejson/commit/cf7d2d1539b262fa26277a22e123fe33041f7710.

**Comment by evanhuang8** [comment]
Thanks. Awesome job guys.

**Comment by Klyyssi** [comment]
@itamarhaber 
Are you sure the documentation was correct and the implementation was incorrect, and not the other way around?

I encountered a problem which would be solved with the old implementation.

The following `EVAL` does not work, since `unpack(a)` is used in the middle of the three arguments. (lua discards all the elements in the list produced by `unpack(a)`, except the first one (3)):

`EVAL 'local a={3,4,5}; return redis.call("JSON.MGET", unpack(a), ".");' 0`


However, this would have worked:

`EVAL 'local a={3,4,5}; return redis.call("JSON.MGET", ".", unpack(a));' 0`

**Comment by Rishu2014** [comment]
How can in get all keys in ReSJON and and also how can i do complex queries .eg.  i have 5 keys say key1 ,key2,key3,key4,key5 having respective json stored against them . now i would like  to find all keys having lest say property name in json having value as 'rishu'

**Comment by sekharchangalaraya** [comment]
Hi Itamar Haber,


we have question.

we are pushing multiple objects into Redis
need to apply filters on the objects

Ex: {"id":1,"name":"David","age":30,"place":"NY","Company":"xyz Company"}
    {"id":2,"name":"William","age":32,"place":"Texas","Company":"abc Company"}
    {"id":3,"name":"Matt","age":30,"place":"Texas","Company":"abc Company"}
    {"id":4,"name":"Clark","age":35,"place":"NY","Company":"xyz Company"}

Question: How to get id s
            1) Select object.id where place='NY' ? expected answer: {1,4}
            2) Select object.id where Company like 'abc*' ? expected answer: {2,3}
            3) select object.id where company like 'abc*' and age > 30?
                expected answer: {2}
