### ISSUE TITLE
STRAPPEND expects JSON string instead of string

### ISSUE THREAD

**Issue by evanhuang8** [RedisLabsModules/rejson#8]
Essentially, it requires the string to append to be "quoted" as if it has been serialized, which is unnecessary, since the key/path to append to should already be a string.

See the following comparisons:

```
127.0.0.1:6380[7]> JSON.SET hello . '"world"'
OK
127.0.0.1:6380[7]> JSON.GET hello .
"\"world\""
127.0.0.1:6380[7]> JSON.STRAPPEND hello . '"peace"'
(integer) 10
127.0.0.1:6380[7]> JSON.SET world . '{"foo":"bar"}'
OK
127.0.0.1:6380[7]> JSON.GET world .foo
"\"bar\""
127.0.0.1:6380[7]> JSON.STRAPPEND world .foo '"t"'
(integer) 4
127.0.0.1:6380[7]> JSON.STRAPPEND world .foo 't'
(error) ERR JSON lexer error SPECIAL_INCOMPLETE at position 1
127.0.0.1:6380[7]> JSON.SET blabh 'blah'
(error) ERR wrong number of arguments for 'JSON.SET' command
127.0.0.1:6380[7]> SET blabh 'blah'
OK
127.0.0.1:6380[7]> GET blabh 'blah'
(error) ERR wrong number of arguments for 'get' command
127.0.0.1:6380[7]> GET blabh
"blah"
```

**Comment by itamarhaber** [comment]
This is a good point, but the current implementation is actually by design and documented in the syntax.

The reason for mandating a `json-string` is to avoid any possible serialization/deserialization issues. The cli has its own way of working with strings, so the single quotes + double quotes is cumbersome but needed. OTOH, when working with regular application clients for Redis, that is a non issue afaik.

**Comment by tony-shannon** [comment]
this appears to be a key issue and one that helps explain a discrepancy in behaviour am seeing by ReJSON from redis-cli and the video on the reJSON docs home page
